apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-demo-quarkus-rest
spec:
  template:
    metadata:
      name: kn-demo-quarkus-rest-v1
      annotations:
        #make it 1 if you don't want coldstart
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      imagePullSecrets:
        - name: myteam-image-repo-secret #{APPTEAM}-
      containers:
        - image: docker.com/ws-quarkus-rest:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"