quarkus:
  log:
    level: INFO
    file:
      enable: true
      async: true
      path: ./logs/cisapi.log
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
    # Configure a named handler that logs to file
    handler:
      file:
        "STRUCTURED_LOGGING_FILE":
          enable: true
          format: "%e%n"
      console:
        "STRUCTURED_LOGGING":
          format: "%e%n"
  category: # Configure the category and link the named handlers to it
    "io.quarkus.category":
      level: INFO
      handlers:
          STRUCTURED_LOGGING,STRUCTURED_LOGGING_FILE
    "org.hibernate":
      level: DEBUG
      handlers:
        STRUCTURED_LOGGING

  swagger-ui:
    always-include: true
  datasource:
    #datasource-cis: #named datasource - not working if it is single ds
    db-kind: oracle
    username: integ
    password: integ123
    jdbc:
      url: jdbc:oracle:thin:@localhost:1521/xe
      max-size: 8
  hibernate-orm:
    #datasource-cis:
    #datasource: "datasource-cis" # defined above
    packages: package model
    database:
      default-schema: integ
      generation: validate # none, create, drop-and-create, drop, update, validate
    log:
      sql: true
    sql-load-script: import.sql

#%prod:
#  quarkus:
#   datasource:
#    db-kind: oracle
#    username: quarkus_test
#    password: quarkus_test
#    jdbc:
#      url: jdbc:oracle://localhost/quarkus_test
#      max-size: 8
#      min-size: 2