#%prod:
#  quarkus:
#   datasource:
#    db-kind: oracle
#    username: quarkus_test
#    password: quarkus_test
#    jdbc:
#      url: jdbc:oracle://localhost/quarkus_test
#      max-size: 8
#      min-size: 2

quarkus:
  swagger-ui:
    always-include: true
  datasource:
    datasource-cis: #named datasource
      db-kind: oracle
      username: integ
      password: integ123
      jdbc:
        url: jdbc:oracle:thin:@localhost:1521/xe
        max-size: 8
  hibernate-orm:
    datasource-cis:
      datasource: "datasource-cis" # defined above
      packages: package model
      database:
        default-schema: integ
        generation: validate # none, create, drop-and-create, drop, update, validate
      log:
        sql: true
      sql-load-script: import.sql
