#%prod:
#  quarkus:
#   datasource:
#    db-kind: oracle
#    username: quarkus_test
#    password: quarkus_test
#    jdbc:
#      url: jdbc:oracle://localhost/quarkus_test
#      max-size: 8
#      min-size: 2

quarkus:
  swagger-ui:
    always-include: true
  datasource:
    db-kind: oracle
    username: ITSEAMINTEG
    password: its3aM#nt3G
    jdbc:
      url: jdbc:oracle:thin:@wwktestdb:1521/wwk
      max-size: 8
      jdbc.min-size: 2
  hibernate-orm:
    database:
      default-schema: APPSCIS
      generation: validate # none, create, drop-and-create, drop, update, validate
    log:
      sql: true
    sql-load-script: import.sql
