apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-kn-event
  namespace: default
spec:
  template:
     metadata:
       annotations:
         #make it 1 if you don't want coldstart
         autoscaling.knative.dev/minScale: "1"
         autoscaling.knative.dev/maxScale: "2"
     spec:
       containers:
          - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest
          - env:
            - name: RESPONSE
            - value: "Hello Serverless!"
