apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  high-availability:
    replicas: 2 # default is 2, putting 1 makes it non-HA
  config:
    tracing:
      sample-rate: "0.1" #means that 1 in 10 traces will be sampled.
      backend: zipkin
      #The zipkin-endpoint must point to your jaeger-collector service endpoint. To get this
      #endpoint, substitute the namespace where the Jaeger CR is applied.
      zipkin-endpoint: http://jaeger-collector.default.svc.cluster.local:9411/api/v2/spans
      #Debugging should be set to false. Enabling debug mode by setting debug: "true" allows all spans to be sent to the server, bypassing sampling.
      debug: "false"
