apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: default
spec:
  #allInOne - nonpersistant, in-emory, suitable for nonprod
  # production - uses persistant elasticsearch.
  strategy: allInOne