create table WO
(
  WO_ID NUMBER(12, 0) primary key
, SVC_PT_ID NUMBER(12, 0) NOT NULL
, EAM_WO VARCHAR2(10 CHAR)
, WO_DT DATE DEFAULT SYSDATE NOT NULL
, WO_DSPTCH_DT DATE
, MTR_WRK_TP_CD VARCHAR2(4 CHAR) DEFAULT 'ZZZZ' NOT NULL
, WO_STAT_CD VARCHAR2(2 CHAR)
, DSPTCH_GRP_CD VARCHAR2(10 CHAR)
, CD_SRC VARCHAR2(10 CHAR)
, FLD_ACT_ID VARCHAR2(10 CHAR)
, CCNB_FA_PR_CD VARCHAR2(2 CHAR)
, CCNB_FA_TP_CD VARCHAR2(8 CHAR)
, CCNB_FA_STAT_CD VARCHAR2(2 CHAR)
, DSPTCH_GRP_EXT_CD VARCHAR2(8 CHAR)
, COMMENTS VARCHAR2(1000 CHAR)
, INSTRUCTIONS VARCHAR2(4000 CHAR)
, NTG_PROJ_CD VARCHAR2(4 CHAR)
, VERSION NUMBER(5, 0) DEFAULT 1
, EWO_PROCESS_IND VARCHAR2(4 CHAR)
, EWO_STAT_CD VARCHAR2(50 CHAR)
, EWO_FEEDBACK_COMMENT VARCHAR2(4000 CHAR)
, MOD_DT DATE DEFAULT SYSDATE NOT NULL
, MOD_BY VARCHAR2(50 CHAR) DEFAULT USER NOT NULL
, ADD_DT DATE DEFAULT SYSDATE NOT NULL
, ADD_BY VARCHAR2(50 CHAR) DEFAULT USER NOT NULL
, MKM_PROJ_CODE VARCHAR2(20 BYTE)
, FLAGGED VARCHAR2(4 BYTE)
, ALT_WO_ID VARCHAR2(10 BYTE)
);

CREATE TABLE INTEG_ADDRESS (
    id  INTEGER -- GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY
    , streetnum VARCHAR(10)
    , streetname VARCHAR(30)
    , city VARCHAR(20)
    , country VARCHAR(20)
    , postalcode VARCHAR(10)
    , lat DECIMAL(8,6)
    , lon DECIMAL(9,6)
    , ts_create TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
    , ts_update TIMESTAMP  DEFAULT CURRENT_TIMESTAMP -- ON UPDATE CURRENT_TIMESTAMP
);